export const data =[
    "This is where it all begins...",
    "Commit committed",
    "Version control is awful",
    "COMMIT ALL THE FILES!",
    "The same thing we do every night, Pinky - try to take over the world!",
    "Lock S-foils in attack position",
    "This commit is a lie",
    "I'll explain when you're older!",
    "Here be Dragons",
    "Reinventing the wheel. Again.",
    "This is not the commit message you are looking for",
    "Batman! (this commit has no parents)",
    "You made the commit but did not uploaded to github, there are bunny's in your code",
    "Coding is my cardio",
    "404: Commit message found, bugs eliminated",
    "In code we trust",
    "Committing changes like a boss",
    "Keep calm and merge conflicts",
    "Code is my happy place",
    "Don't just fix the bug, understand why it's there",
    "Roses are red, violets are blue, unexpected '{' on line 32",
    "Life is short, commit often",
    "Code never lies, comments sometimes do",
    "Push it real good",
    "When in doubt, commit it out",
    "It's not a bug, it's a feature!",
    "With great code comes great responsibility",
        "Roses are red, violets are blue, unexpected token '}' on line 32",
        "To infinity and beyond... nested loops!",
        "I've got 99 problems, but a bug ain't one... said no programmer ever",
        "Programming: turning caffeine into code since the beginning of time",
        "Life is short, talk is cheap. Code is long, bugs are deep",
        "I'm not lazy, I'm just on energy-saving mode",
        "I speak fluent JavaScript and sarcasm",
        "I put the 'fun' in 'function'",
        "Commit early, commit often... unless you're in a relationship",
        "Error 404: Sense of humor not found",
        "I'm not anti-social; I'm just not user-friendly",
        "If at first, you don't succeed, call it version 1.0",
        "The only time success comes before work is in the dictionary",
        "Code like a butterfly, sting like a bee",
        "I'm not a great programmer; I'm just a good programmer with great habits",
        "I'm not a control freak, but can I show you the right way to do that?",
        "Code is poetry in motion... until it crashes",
        "I don't always test my code, but when I do, I do it in production",
        "Debugging is like hunting for a needle in a haystack... except the needle is also a bug",
        "Programmers don't die, they just GOTO hell",
        "I code, therefore I am... caffeinated",
        "The code is strong with this one",
        "I'm not a programmer; I just code a lot",
        "My code is like a fine wine; it only gets better with age... until it turns into vinegar",
        "Programmers don't make mistakes, they have unexpected features",
        "Keep calm and console.log()",
        "I'm not a nerd; I'm just smarter than you",
        "I'm not paid to code; I'm paid to debug",
        "I don't need Google; my code knows everything",
        "I'm not addicted to programming; I'm committed",
        "I'm not antisocial; I'm just not user-friendly",
        "I would tell you a joke about UDP, but you might not get it",
        "I'm not lazy, I'm on energy-saving mode",
        "If you think coding is easy, try debugging",
        "Sleep is for the weak; debugging is for the strong",
        "I'm not antisocial; I'm just busy refactoring",
        "I'm not a nerd; I'm just intellectually gifted",
        "Programming is like sex: one mistake and you have to support it for the rest of your life",
        "I'm not a control freak; I'm just better at programming than you",
        "I don't always code, but when I do, I prefer JavaScript",
        "Keep calm and commit often",
        "I'm not a great programmer; I'm just a good programmer with great habits",
        "I'm not a hacker; I'm just a programmer with unauthorized access",
        "If at first, you don't succeed, call it version 1.0",
        "I'm not antisocial; I'm just busy debugging",
        "I'm not lazy; I'm just in a parallel universe",
        "I don't always write code, but when I do, I prefer JavaScript",
        "I'm not a control freak; I'm just better at programming than you",
        "I don't always test my code, but when I do, I do it in production",
        "Debugging is like hunting for a needle in a haystack... except the needle is also a bug",
        "I'm not a hacker; I'm just a programmer with unauthorized access",
        "I don't always code, but when I do, I prefer Python",
        "I don't always write code, but when I do, I prefer Python",
        "I'm not a nerd; I'm just intellectually gifted",
        "I'm not a great programmer; I'm just a good programmer with great habits",
        "I'm not antisocial; I'm just busy debugging",
        "I'm not lazy; I'm just in a parallel universe",
        "I don't always test my code, but when I do, I do it in production",
        "Debugging is like hunting for a needle in a haystack... except the needle is also a bug",
        "I'm not a hacker; I'm just a programmer with unauthorized access",
        "I don't always code, but when I do, I prefer Python",
        "I don't always write code, but when I do, I prefer Python",
        "I'm not a nerd; I'm just intellectually gifted",
        "I'm not a great programmer; I'm just a good programmer with great habits",
        "I'm not antisocial; I'm just busy debugging",
        "I'm not lazy; I'm just in a parallel universe",
        "I don't always test my code, but when I do, I do it in production",
        "Debugging is like hunting for a needle in a haystack... except the needle is also a bug",
        "I'm not a hacker; I'm just a programmer with unauthorized access",
        "I don't always code, but when I do, I prefer Python",
        "I don't always write code, but when I do, I prefer Python",
        "I'm not a nerd; I'm just intellectually gifted",
        "I'm not a great programmer; I'm just a good programmer with great habits",
        "I'm not antisocial; I'm just busy debugging",
        "I'm not lazy; I'm just in a parallel universe",
        "I don't always test my code, but when I do, I do it in production",
        "Debugging is like hunting for a needle in a haystack... except the needle is also a bug",
        "I'm not a hacker; I'm just a programmer with unauthorized access",
        "I don't always code, but when I do, I prefer Python",
        "I don't always write code, but when I do, I prefer Python",
        "I'm not a nerd; I'm just intellectually gifted",
        "I'm not a great programmer; I'm just a good programmer with great habits",
        "I'm not antisocial; I'm just busy debugging",
        "I'm not lazy; I'm just in a parallel universe",
        "I don't always test my code, but when I do, I do it in production",
        "Debugging is like hunting for a needle in a haystack... except the needle is also a bug",
        "I'm not a hacker; I'm just a programmer with unauthorized access",
        "I don't always code, but when I do, I prefer Python",
        "I don't always write code, but when I do, I prefer Python",
        "I'm not a nerd; I'm just intellectually gifted",
        "I'm not a great programmer; I'm just a good programmer with great habits",
        "I'm not antisocial; I'm just busy debugging",
        "I'm not lazy; I'm just in a parallel universe"
]

export const encouragementMessageData = [
    "You are a good coder ussing npm",
    "where did you learn how to code",
    "You're not a coder and you write code well",
    "You have a salary increase",
    "You are submited to another position",
    "Keep coding and carry on!",
    "You're debugging like a boss!",
    "Don't worry, even the best programmers make typos.",
    "You're a coding wizard!",
    "If at first you don't succeed, try, try, and try a hundred times more.",
    "Remember, every bug you fix makes your code stronger.",
    "You're not stuck, you're just improving your problem-solving skills.",
    "You're so good at coding, even your bugs have bugs!",
    "Keep calm and keep coding.",
    "The only way to fail is to stop trying... or to forget a semicolon.",
    "Don't let bugs bug you!",
    "You're coding at the speed of light!",
    "Stay determined, you're closer to success than you think.",
    "You're coding circles around everyone else!",
    "Every error message is just a stepping stone to success.",
    "You're not lost, you're just exploring new debugging techniques.",
    "You're making the world a better place, one line of code at a time.",
    "Embrace the bugs, they're just opportunities to learn.",
    "Even a journey of a thousand miles begins with a single line of code.",
    "You're not procrastinating, you're just letting your code marinate.",
    "Your code is like fine wine, it gets better with age... or at least with debugging.",
    "You're not failing, you're just discovering what doesn't work.",
    "Keep your head high and your code clean.",
    "You're not alone, Stack Overflow is just a tab away.",
    "Your code is as elegant as a well-crafted haiku.",
    "Don't let imposter syndrome get you down, you're a coding rockstar!",
    "You're debugging with the grace of a ninja.",
    "Every bug you squash is a victory for programmers everywhere.",
    "You're not just writing code, you're crafting digital art.",
    "Keep coding, the world needs your creativity!",
    "You're a debugging superhero!",
    "Remember, the darkest bugs make the brightest stars.",
    "You're not failing, you're experimenting with style.",
    "Keep calm and refactor on!",
    "You're coding with the wisdom of a thousand sages.",
    "Every keystroke brings you closer to greatness.",
    "You're not struggling, you're just giving the bugs a fighting chance.",
    "You're debugging like a pro!",
    "You're not lost, you're just taking the scenic route to success.",
    "You're coding with the precision of a Swiss watchmaker.",
    "Don't give up, your breakthrough is just around the corner.",
    "You're not making mistakes, you're just adding character to your code.",
    "Keep coding and carry on!",
    "You're debugging like a boss!",
    "Don't worry, even the best programmers make typos.",
    "You're a coding wizard!",
    "If at first you don't succeed, try, try, and try a hundred times more.",
    "Remember, every bug you fix makes your code stronger.",
    "You're not stuck, you're just improving your problem-solving skills.",
    "You're so good at coding, even your bugs have bugs!",
    "Keep calm and keep coding.",
    "The only way to fail is to stop trying... or to forget a semicolon.",
    "Don't let bugs bug you!",
    "You're coding at the speed of light!",
    "Stay determined, you're closer to success than you think.",
    "You're coding circles around everyone else!",
    "Every error message is just a stepping stone to success.",
    "You're not lost, you're just exploring new debugging techniques.",
    "You're making the world a better place, one line of code at a time.",
    "Embrace the bugs, they're just opportunities to learn.",
    "Even a journey of a thousand miles begins with a single line of code.",
    "You're not procrastinating, you're just letting your code marinate.",
    "Your code is like fine wine, it gets better with age... or at least with debugging.",
    "You're not failing, you're just discovering what doesn't work.",
    "Keep your head high and your code clean.",
    "You're not alone, Stack Overflow is just a tab away.",
    "Your code is as elegant as a well-crafted haiku.",
    "Don't let imposter syndrome get you down, you're a coding rockstar!",
    "You're debugging with the grace of a ninja.",
    "Every bug you squash is a victory for programmers everywhere.",
    "You're not just writing code, you're crafting digital art.",
    "Keep coding, the world needs your creativity!",
    "You're a debugging superhero!",
    "Remember, the darkest bugs make the brightest stars.",
    "You're not failing, you're experimenting with style.",
    "Keep calm and refactor on!",
    "You're coding with the wisdom of a thousand sages.",
    "Every keystroke brings you closer to greatness.",
    "You're not struggling, you're just giving the bugs a fighting chance.",
    "You're debugging like a pro!",
    "You're not lost, you're just taking the scenic route to success.",
    "You're coding with the precision of a Swiss watchmaker.",
    "Don't give up, your breakthrough is just around the corner.",
    "You're not making mistakes, you're just adding character to your code."
]